version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./lmw/:/var/www/html
    environment:
      - APP_ENV=local
    networks:
      - my-network
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    external: true