version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./lmw/:/var/www/html
    environment:
      - APP_ENV=local
#      - APP_KEY=base64:your_generated_key_here
#      - DB_CONNECTION=mongodb
#      - DB_HOST=mongodb
#      - DB_PORT=27017
#      - DB_DATABASE=order-tracker
#      - DB_USERNAME=
#      - DB_PASSWORD=
    networks:
      - my-network

#  mongodb:
#    image: mongo:latest
#    ports:
#      - "27017:27017"
#    networks:
#      - my-network

networks:
  my-network:
    external: true